# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php 
php: 
 - 5.3

env:
 - DB=MYSQL CORE_RELEASE=3.1
 - DB=PGSQL CORE_RELEASE=3.1

before_script:
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require "silverstripe/subsites"
 - cd ~/builds/ss

script: 
 - var/bin/phpunit securityreport/tests/
